export const ADDITEM = "ADDITEM";
export const REMOVEITEM = "REMOVEITEM";
export const UPDATEITEM = "UPDATEITEM";
export const SETCOMPLETEDITEM = 'SETCOMPLETEDITEM';
export const DELETEITEMS = "DELETEITEMS";